export default [
  'Nobody is Coming.',
  'The present is shaping the future.',
  'The future is already here.',
  'Never Settle.',
  'Thrust yourself.',
  'The key is in your hands.',
  'Action is the antidote to fear.',
  'Dreams demand effort.',
  'What you seek is seeking you.',
  'Courage is a muscle; use it.',
  'Stop waiting, start doing.',
  'Your potential is limitless.',
  'One step changes everything.',
  'Discomfort breeds growth.',
  'You are your best investment.',
  'Own your narrative.',
  'Time respects no one.',
  'The harder the climb, the better the view.',
  'Trust the process.',
  'No one will fight harder than you.',
  'Your past does not define you.',
  'You are the solution.',
  'Fail fast, learn faster.',
  'Action ignites clarity.',
  'No shortcuts to excellence.',
  'Progress, not perfection.',
  'Every moment counts.',
  'Energy flows where focus goes.',
  'Fear is fuel.',
  'Stay hungry, stay foolish.',
  'Greatness demands sacrifices.',
  'Define your purpose.',
  'Break the chains of doubt.',
  'Your limits are imagined.',
  'The grind knows no glory.',
  'Create your own momentum.',
  'Do the work, embrace the reward.',
  'Success loves preparation.',
  'Stop overthinking, start executing.',
  'No one owes you anything.',
  'Decisions shape destiny.',
  'Consistency is king.',
  'Adversity is your ally.',
  'Build or be built.',
  'Discipline unlocks freedom.',
  'Small wins compound greatness.',
  'Start where you are.',
  'Clarity breeds confidence.',
  'Rise above the noise.',
  'Excuses don’t build empires.'
];
