export default [
  'Ninguém virá.',
  'O presente está moldando o futuro.',
  'O futuro já está aqui.',
  'Nunca se acomode.',
  'Confie em si mesmo.',
  'A chave está em suas mãos.',
  'A ação é o antídoto para o medo.',
  'Sonhos exigem esforço.',
  'O que você busca está buscando você.',
  'Coragem é um músculo; use-o.',
  'Pare de esperar, comece a agir.',
  'Seu potencial é ilimitado.',
  'Um passo muda tudo.',
  'O desconforto gera crescimento.',
  'Você é seu melhor investimento.',
  'Assuma o controle da sua história.',
  'O tempo não respeita ninguém.',
  'Quanto mais difícil a subida, melhor a vista.',
  'Confie no processo.',
  'Ninguém lutará mais por você do que você mesmo.',
  'Seu passado não define você.',
  'Você é a solução.',
  'Falhe rápido, aprenda mais rápido.',
  'Ação traz clareza.',
  'Não há atalhos para a excelência.',
  'Progresso, não perfeição.',
  'Cada momento conta.',
  'A energia flui para onde vai o foco.',
  'O medo é combustível.',
  'Mantenha a fome, mantenha a ingenuidade.',
  'A grandeza exige sacrifícios.',
  'Defina seu propósito.',
  'Quebre as correntes da dúvida.',
  'Seus limites são imaginários.',
  'O esforço não busca glória.',
  'Crie seu próprio momento.',
  'Faça o trabalho, aproveite a recompensa.',
  'O sucesso ama a preparação.',
  'Pare de pensar demais, comece a executar.',
  'Ninguém lhe deve nada.',
  'As decisões moldam o destino.',
  'A consistência é rei.',
  'A adversidade é sua aliada.',
  'Construa ou será construído.',
  'A disciplina libera a liberdade.',
  'Pequenas vitórias constroem grandeza.',
  'Comece de onde você está.',
  'Clareza gera confiança.',
  'Supere o ruído.',
  'Desculpas não constroem impérios.'
];
